### ISSUE TITLE
Proposal to Switch from Quartz to Starlight for the Website

### ISSUE THREAD

**Issue by trueberryless** [n0rwin/deep-thought#1]
**Summary:** 
I would like to propose switching the website framework from [Quartz](https://quartz.jzhao.xyz/) to [Starlight](https://starlight.astro.build/). Starlight offers a more modern design, improved features, and an enhanced user experience. Additionally, it now includes an [Obsidian plugin](https://github.com/HiDeoo/starlight-obsidian) and [View Modes (from me)](https://starlight-view-modes.trueberryless.org/), which could be incredibly useful for you.

**Details:**  
- **Visual Appeal:** 
Starlight provides a more polished and aesthetically pleasing design compared to Quartz. This could enhance the overall appearance of the website, making it more engaging for visitors.
 
- **Improved Features:** 
Starlight offers a range of features that can improve both the functionality and the user experience of the website. This includes better support for various content types and an overall more intuitive user interface.
 
- **Obsidian Plugin:** 
One of the standout features of Starlight is its integration with Obsidian through a dedicated plugin. Given your usage of Obsidian for notes and content organization, this plugin could streamline your workflow by allowing you to directly publish or update content on the website from within Obsidian.

- **Starlight View Modes Plugin:** 
I have developed a plugin called "Starlight View Modes" that enhances the website with a "Zen Mode" for distraction-free reading and a "Presentation Mode" (coming soon) for delivering content in a slideshow format. This plugin could add valuable new ways to interact with the website's content.

**Why Starlight Over Quartz:** 
While Quartz has served its purpose well, Starlight’s modern design, enhanced features, and Obsidian integration offer significant advantages that could improve both the backend management and frontend user experience of the website.

**Conclusion:** 
I believe that making the switch to Starlight could be highly beneficial. It would modernize the website, provide additional useful features, and integrate seamlessly with tools like Obsidian that you already use.

Please let me know your thoughts on this, and if you would like any assistance with the migration process.

---

Thank you for considering this suggestion!

**Comment by n0rwin** [comment]
I made the switch to starlight. Thanks for your suggestion and the hint for the obsidian plugin. However in the course of the migration i decided not to host the website via github pages anymore. Therefore I will close this repository. I plan on open-sourcing the obsidian vault in a public github repository though. Link will be provided on the deep-thought.norwin.at website.

**Comment by trueberryless** [comment]
Wonderful!

I'm currently trying to work on a presentation mode plugin for Starlight. If you want to add that to your website, I'll let you know if I'm done programming it.
